### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [NielsMasdorp/Nederadio-Android#31]
Just wondering whether this project is still maintained, as the last commit was more than 2 years ago?

**Comment by IzzySoft** [comment]
@NielsMasdorp ^^? Does "no answer" mean "not maintained anymore"?

**Comment by NielsMasdorp** [comment]
Hi, sorry for the late response.
The project is not maintained anymore. Unfortunately Google decided to remove the app from the Play Store for violating some stuff. Do you have feature requests?

**Comment by IzzySoft** [comment]
Yeah, Google is known for such things – though I have no idea why they should have pulled yours, I see nothing violating.

Your app is still available [via my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/index/apk/com.nielsmasdorp.sleeply) (and could even make it to the official repo were it not for Crashlytics). I will update its description then and point here. Maybe you should also mention the fact it's no longer maintained in the README, or archive the repo to indicate it.

Don't give up. There's also F-Droid (and my repo with a [less strict inclusion policy](https://gitlab.com/IzzyOnDroid/repo). Feel free to ping me if you want an app integrated, @NielsMasdorp – and thanks for your app and your reply!
