### ISSUE TITLE
Android Auto - Missing latest playable

### ISSUE THREAD

**Issue by PaulWoitaschek** [NielsMasdorp/Nederadio-Android#42]
This was originally reported here: https://github.com/PaulWoitaschek/Voice/issues/1765 but as I'm stuck and your project is the only other media3 session App on Github I figured that you might have an idea:

When nederadio is not running and you start Android Auto, the recent playing item is gone:

## Reproducer
* Install Version 2.2.2
* Play a radio station, pause it.
* Run the DHU: `desktop-head-unit --usb`
* Now Nederadio is show in Android Auto
<img width="320" alt="grafik" src="https://github.com/NielsMasdorp/Nederadio-Android/assets/743462/e84b790f-ffef-4d2f-9b86-b9c4a48a395c">

* Close DHU
* Kill the app (Settings - Force Stop)
* Open the DHU
* Now instead of the last items it shows "Tap to open"
<img width="320" alt="grafik" src="https://github.com/NielsMasdorp/Nederadio-Android/assets/743462/6324513e-d857-4967-b0a2-253ca37bea9b">

Other apps (you can repeat these steps with Pocket Casts) manage to show the recently played item:

<img width="320" alt="grafik" src="https://github.com/NielsMasdorp/Nederadio-Android/assets/743462/bf67a977-30db-4288-87da-5fc04295e731">

**Comment by PaulWoitaschek** [comment]
Update, I found a simpler reproducer:

## Reproducer
* Install Version 2.2.2
* Run the DHU: `desktop-head-unit --usb`
* Play a radio station, pause it.
* Now Nederadio is show in Android Auto
<img width="320" alt="grafik" src="https://github.com/NielsMasdorp/Nederadio-Android/assets/743462/e84b790f-ffef-4d2f-9b86-b9c4a48a395c">

* Kill the app (Settings - Force Stop)
* It loads
* Now instead of the last items it shows "Tap to open"
<img width="320" alt="grafik" src="https://github.com/NielsMasdorp/Nederadio-Android/assets/743462/6324513e-d857-4967-b0a2-253ca37bea9b">

**Comment by NielsMasdorp** [comment]
Hi @PaulWoitaschek apologies for not replying sooner, I was not notified of your issue. Thanks for looking out! I've fixed the issue per [2fafda6](https://github.com/NielsMasdorp/Nederadio-Android/commit/2fafda63234bc351646dabfab8e78901b8d68a9f). I've looked at your solution and implemented it. Thanks again!
